import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@fontsource/lato/100.css";
import "@fontsource/lato/300.css";
import "@fontsource/lato/400.css";
import "@fontsource/lato/700.css";
// import '@fontsource/lato/900.css';
import "./globals.css";
import Navbar from "../components/molecules/navbar/navbar";
import MaterialThemeProvider from "../components/theme/materialThemeProvider";
import BottomBar from "@/components/molecules/navbar/bottomBar";
import { Box, StyledEngineProvider } from "@mui/material";

export const metadata: Metadata = {
  title: "HomeKeep",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: any;
  // React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MaterialThemeProvider>
          <StyledEngineProvider injectFirst>
            <Navbar />
          </StyledEngineProvider>
          <Box mt={{xs:8, md:8, lg:10}}>{children}</Box>
          <BottomBar />
        </MaterialThemeProvider>
      </body>
    </html>
  );
}
